In [8]:
import pandas as pd

In [9]:
df=pd.read_csv("pandas_docs/survey_results_public.csv")
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [10]:
ef=pd.read_csv("pandas_docs/survey_results_schema.csv")
ef

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

# retrieve first 5 rows with all columns|

In [4]:
df.iloc[[0,1,2,3,4,5],:]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
5,6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult

# retrieve respondents 450,900,1350 with only their country,Hobbyist,YearsCode,Age1stCode|

In [10]:
df.columns.get_loc("Country")

6

In [11]:
df.columns.get_loc("Hobbyist")

2

In [87]:
df.columns.get_loc("YearsCode")

13

In [88]:
df.columns.get_loc("Age1stCode")

14

In [89]:
df.iloc[[450,900,1350],[6,2,13,14]]

            Country Hobbyist YearsCode Age1stCode
450   United States      Yes         7         28
900            Iran      Yes         6         16
1350         Mexico      Yes        10          9

# retrieve respondent 500 and his age

In [91]:
df.columns.get_loc("Age")

77

In [92]:
df.iloc[500,77]

21.0

# 1000t row > Country

In [12]:
df.loc[1000,"Country"]

'United Kingdom'

# 30th row > Hobbyist

In [13]:
df.loc[30,"Hobbyist"]

'No'

# 300th row >devtype

In [15]:
df.loc[300,"DevType"]

'Developer, back-end;Developer, desktop or enterprise applications;Developer, game or graphics'

# acess 50-150

In [16]:
df.iloc[50:150]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
50,51,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,United States,"Yes, full-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers,18.0,Woman,No,Straight / Heterosexual,South Asian,No,Too long,Easy
51,52,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Poland,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,A lot less welcome now than last year,NaN,22.0,Man,No,NaN,NaN,No,Appropriate in length,Neither easy nor difficult
52,53,"I am not primarily a developer, but I write co...",Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
53,54,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Sweden,No,NaN,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,37.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
54,55,I am a student who is learning to code,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Sri Lanka,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,25.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,147,I am a developer by profession,No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Argentina,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,No,Appropriate in length,Easy
146,148,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,28.0,Woman,No,Gay or Lesbian,Black or of African descent,No,Appropriate in length,Neither easy nor difficult
147,149,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Austria,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",...,NaN,NaN,40.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Neither easy nor difficult
148,150,I am a developer by profession,Yes,Never,NaN,Employed full-time,Croatia,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,31.0,Woman,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Neither easy nor difficult
149,151,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Romania,"Yes, part-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too short,Easy

# acess without starting point

In [17]:
df.iloc[:150]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,147,I am a developer by profession,No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Argentina,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,No,Appropriate in length,Easy
146,148,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,28.0,Woman,No,Gay or Lesbian,Black or of African descent,No,Appropriate in length,Neither easy nor difficult
147,149,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Austria,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",...,NaN,NaN,40.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Neither easy nor difficult
148,150,I am a developer by profession,Yes,Never,NaN,Employed full-time,Croatia,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,31.0,Woman,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Neither easy nor difficult
149,151,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Romania,"Yes, part-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too short,Easy

# acess without ending point

In [18]:
df.iloc[50:]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
50,51,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,United States,"Yes, full-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers,18.0,Woman,No,Straight / Heterosexual,South Asian,No,Too long,Easy
51,52,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Poland,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,A lot less welcome now than last year,NaN,22.0,Man,No,NaN,NaN,No,Appropriate in length,Neither easy nor difficult
52,53,"I am not primarily a developer, but I write co...",Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
53,54,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Sweden,No,NaN,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,37.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
54,55,I am a student who is learning to code,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Sri Lanka,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,25.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

# Retrieve 1000th respondent with his salary and Country he belongs from

In [19]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [20]:
df.loc[1000,["ConvertedComp","Country"]]

ConvertedComp          130847.0
Country          United Kingdom
Name: 1000, dtype: object

# Retrieve top 45 rows form first 5 columns and return their data type(do this on top 2 different data sets)

In [28]:
h=df.iloc[:45,:5]
h

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro..."
5,6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...
6,7,I am a developer by profession,No,Never,The quality of OSS and closed source software ...
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro..."
8,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...
9,10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro..."
10,11,I code primarily as a hobby,Yes,Once a month or more often,The quality of OSS and closed source software ...
11,12,I am a student who is learning to code,No,Never,"OSS is, on average, of HIGHER quality than pro..."
12,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro..."
13,14,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...
14,15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro..."
15,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...
16,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...
17,18,"I am not primarily a developer, but I write co...",Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...
18,19,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...
19,20,"I am not primarily a developer, but I write co...",No,Never,"OSS is, on average, of HIGHER quality than pro..."
20,21,I code primarily as a hobby,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro..."
21,22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro..."
22,23,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...
23,24,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro..."
24,25,I am a developer by profession,No,Never,"OSS is, on average, of HIGHER quality than pro..."
25,26,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...
26,27,"I used to be a developer by profession, but no...",Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro..."
27,28,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...
28,29,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro..."
29,30,I am a developer by profession,No,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro..."
30,31,I am a student who is learning to code,No,Never,NaN
31,32,I am a developer by profession,No,Never,The quality of OSS and closed source software ...
32,33,I am a developer by profession,No,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro..."
33,34,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro..."
34,35,I am a developer by profession,No,Never,"OSS is, on average, of HIGHER quality than pro..."
35,36,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...
36,37,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop..."
37,38,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop..."
38,39,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...
39,40,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro..."
40,41,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro..."
41,42,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro..."
42,43,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro..."
43,44,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...
44,45,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...

In [29]:
h.dtypes

Respondent      int64
MainBranch     object
Hobbyist       object
OpenSourcer    object
OpenSource     object
dtype: object

In [30]:
r=pd.read_csv("Fifa_world_cup_matches.csv")
r

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,ENGLAND,FRANCE,54%,36%,10%,1,2,10 DEC 2022,20 : 00,Quarter-final,...,1,0,9,15,0,0,49,54,193,308
60,ARGENTINA,CROATIA,34%,54%,12%,3,0,13 DEC 2022,20 : 00,Semi-final,...,1,0,12,10,0,0,85,63,321,260
61,FRANCE,MOROCCO,34%,55%,11%,2,0,14 DEC 2022,20 : 00,Semi-final,...,0,0,13,14,0,0,72,47,328,218
62,CROATIA,MOROCCO,45%,45%,10%,2,1,17 DEC 2022,16 : 00,Play-off for third place,...,0,0,7,14,0,0,75,72,288,277
63,ARGENTINA,FRANCE,46%,40%,14%,3,3,18 DEC 2022,16 : 00,Final,...,1,2,11,21,0,0,87,104,280,409

In [33]:
s=r.iloc[:45,:5]
s

,team1,team2,possession team1,possession team2,possession in contest
0,QATAR,ECUADOR,42%,50%,8%
1,ENGLAND,IRAN,72%,19%,9%
2,SENEGAL,NETHERLANDS,44%,45%,11%
3,UNITED STATES,WALES,51%,39%,10%
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%
5,DENMARK,TUNISIA,55%,33%,12%
6,MEXICO,POLAND,54%,31%,15%
7,FRANCE,AUSTRALIA,56%,35%,9%
8,MOROCCO,CROATIA,32%,57%,12%
9,GERMANY,JAPAN,65%,22%,13%
10,SPAIN,COSTA RICA,74%,17%,9%
11,BELGIUM,CANADA,46%,43%,11%
12,SWITZERLAND,CAMEROON,43%,46%,11%
13,URUGUAY,KOREA REPUBLIC,49%,38%,13%
14,PORTUGAL,GHANA,55%,35%,10%
15,BRAZIL,SERBIA,53%,34%,13%
16,WALES,IRAN,51%,33%,16%
17,QATAR,SENEGAL,42%,48%,10%
18,NETHERLANDS,ECUADOR,48%,39%,13%
19,ENGLAND,UNITED STATES,51%,40%,9%
20,TUNISIA,AUSTRALIA,50%,31%,19%
21,POLAND,SAUDI ARABIA,30%,57%,14%
22,FRANCE,DENMARK,44%,44%,12%
23,ARGENTINA,MEXICO,50%,36%,14%
24,JAPAN,COSTA RICA,48%,39%,13%
25,BELGIUM,MOROCCO,56%,32%,12%
26,CROATIA,CANADA,41%,46%,13%
27,SPAIN,GERMANY,56%,33%,11%
28,CAMEROON,SERBIA,38%,49%,13%
29,KOREA REPUBLIC,GHANA,53%,32%,15%
30,BRAZIL,SWITZERLAND,51%,40%,9%
31,PORTUGAL,URUGUAY,53%,35%,12%
32,NETHERLANDS,QATAR,54%,38%,8%
33,ECUADOR,SENEGAL,51%,32%,17%
34,WALES,ENGLAND,33%,58%,10%
35,IRAN,UNITED STATES,42%,45%,13%
36,AUSTRALIA,DENMARK,24%,60%,16%
37,TUNISIA,FRANCE,30%,56%,14%
38,POLAND,ARGENTINA,24%,67%,9%
39,SAUDI ARABIA,MEXICO,29%,55%,17%
40,CROATIA,BELGIUM,43%,47%,10%
41,CANADA,MOROCCO,52%,36%,12%
42,JAPAN,SPAIN,14%,78%,8%
43,COSTA RICA,GERMANY,27%,60%,13%
44,GHANA,URUGUAY,46%,39%,15%

In [34]:
s.dtypes

team1                    object
team2                    object
possession team1         object
possession team2         object
possession in contest    object
dtype: object

# - Retrieve Multiple columns with multiple rows from two dataframes

In [36]:
df.iloc[[1,4,5],[4,5,3]]

,OpenSource,Employment,OpenSourcer
1,The quality of OSS and closed source software ...,"Not employed, but looking for work",Less than once per year
4,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Once a month or more often
5,The quality of OSS and closed source software ...,Employed full-time,Never

In [37]:
r.iloc[[1,3,4],[2,3,4]]

  possession team1 possession team2 possession in contest
1              72%              19%                    9%
3              51%              39%                   10%
4              64%              24%                   12%

# Retrieve last 5 rows and last 5 columns and return their column names only

In [39]:
v=df.iloc[-5:,-5:]
v

,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
88878,NaN,NaN,No,Appropriate in length,Easy
88879,NaN,NaN,NaN,NaN,NaN
88880,NaN,NaN,NaN,NaN,NaN
88881,NaN,NaN,NaN,NaN,NaN
88882,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [40]:
v.columns

Index(['Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'], dtype='object')

# get the index postition any column

In [43]:
v.columns.get_loc("Sexuality")

0

# Create a dictionary which contains keys> Name, Marks,Result

In [58]:
dict1={"Name":["adnan","messi","ronaldo"],"Marks":[98,74,97],"result":["pass","pass","pass"]}
dict1

{'Name': ['adnan', 'messi', 'ronaldo'],
 'Marks': [98, 74, 97],
 'result': ['pass', 'pass', 'pass']}

# convert dictionary into dataframe

In [59]:
d=pd.DataFrame(dict1)
d

      Name  Marks result
0    adnan     98   pass
1    messi     74   pass
2  ronaldo     97   pass

# Access values using square barackets

In [52]:
d["Name"]

0      adnan
1      messi
2    ronaldo
Name: Name, dtype: object

# access values using iloc

In [53]:
d.iloc[2]

Name      ronaldo
Marks          97
result       pass
Name: 2, dtype: object

# access values using loc

In [61]:
d.loc[1,"Marks"]

74

# Create a data frame which inlcudes a columns with serial number and id columns

In [11]:
dict1={"Name":["adnan","messi","ronaldo"],"Marks":[98,74,97],"result":["pass","pass","pass"],"serialno":[1,2,3],"id":["a","b","c"]}
dict1

{'Name': ['adnan', 'messi', 'ronaldo'],
 'Marks': [98, 74, 97],
 'result': ['pass', 'pass', 'pass'],
 'serialno': [1, 2, 3],
 'id': ['a', 'b', 'c']}

In [22]:
i=pd.DataFrame(dict1)
i

      Name  Marks result  serialno id
0    adnan     98   pass         1  a
1    messi     74   pass         2  b
2  ronaldo     97   pass         3  c

# make serial column as an index

In [23]:
i.set_index("serialno",inplace=True)

In [24]:
i

             Name  Marks result id
serialno
1           adnan     98   pass  a
2           messi     74   pass  b
3         ronaldo     97   pass  c

# acess values

In [27]:
i.loc[1]

Name      adnan
Marks        98
result     pass
id            a
Name: 1, dtype: object

# make id column into index

In [28]:
i.set_index("id",inplace=True)

In [29]:
i

       Name  Marks result
id
a     adnan     98   pass
b     messi     74   pass
c   ronaldo     97   pass

# access value

In [30]:
i.loc["b"]

Name      messi
Marks        74
result     pass
Name: b, dtype: object

# On survery Data

## How old all the fist 30 respondents

In [72]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [73]:
df.loc[:30,"Age"]

0     14.0
1     19.0
2     28.0
3     22.0
4     30.0
5     28.0
6     42.0
7     24.0
8     23.0
9      NaN
10    22.0
11    21.0
12    28.0
13    31.0
14    20.0
15    26.0
16    29.0
17     NaN
18    31.0
19    38.0
20     NaN
21    47.0
22    22.0
23    23.0
24    22.0
25    34.0
26    22.0
27     NaN
28    32.0
29    28.0
30     NaN
Name: Age, dtype: float64

## Preferred gender of 50 to 100 respondents

In [74]:
df.loc[50:100,"Gender"]

50                                                 Woman
51                                                   Man
52                                                   Man
53                                                   Man
54                                                   Man
55                                                   Man
56                                                   Man
57                                                   Man
58                                                   Man
59                                                   Man
60                                                   Man
61                                                   Man
62                                                   Man
63                                                   Man
64                                                   Man
65                                                   NaN
66                                                   Man
67                                                   Man
68                                                   Man
69                                                   Man
70                                                 Woman
71                                                   Man
72                                                   Man
73                                                   Man
74                                                 Woman
75                                                   Man
76                                                   Man
77                                                   Man
78                                                   Man
79                                                   Man
80                                                   Man
81                                                   Man
82                                                   Man
83                                                   Man
84                                                   Man
85                                                 Woman
86                                                   Man
87                                                   Man
88                                                   Man
89                                                   Man
90                                                   Man
91                                                   Man
92                                                   NaN
93                                                   Man
94                                                   Man
95                                                   Man
96     Non-binary, genderqueer, or gender non-conforming
97                                                   Man
98                                                   Man
99                                                 Woman
100                                                  NaN
Name: Gender, dtype: object

## Most number of respondents are from which country

In [11]:
df["Country"].value_counts()

Country
United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: count, Length: 179, dtype: int64

## EdLevel and YearsCodPro of 1000 to 1050

In [84]:
df.loc[1000:1050,["EdLevel","YearsCodePro"]]

                                                EdLevel      YearsCodePro
1000           Bachelor’s degree (BA, BS, B.Eng., etc.)                10
1001        Master’s degree (MA, MS, M.Eng., MBA, etc.)                 2
1002           Bachelor’s degree (BA, BS, B.Eng., etc.)                 3
1003  Some college/university study without earning ...                 5
1004  Some college/university study without earning ...                20
1005           Bachelor’s degree (BA, BS, B.Eng., etc.)                 4
1006        Master’s degree (MA, MS, M.Eng., MBA, etc.)                 6
1007        Master’s degree (MA, MS, M.Eng., MBA, etc.)                 2
1008  Some college/university study without earning ...                 2
1009           Bachelor’s degree (BA, BS, B.Eng., etc.)  Less than 1 year
1010        Master’s degree (MA, MS, M.Eng., MBA, etc.)                 7
1011        Master’s degree (MA, MS, M.Eng., MBA, etc.)                12
1012  Some college/university study without earning ...                 4
1013           Bachelor’s degree (BA, BS, B.Eng., etc.)                 6
1014           Bachelor’s degree (BA, BS, B.Eng., etc.)               NaN
1015           Bachelor’s degree (BA, BS, B.Eng., etc.)                 5
1016           Bachelor’s degree (BA, BS, B.Eng., etc.)               NaN
1017  Some college/university study without earning ...                21
1018        Master’s degree (MA, MS, M.Eng., MBA, etc.)                 2
1019        Master’s degree (MA, MS, M.Eng., MBA, etc.)                10
1020           Bachelor’s degree (BA, BS, B.Eng., etc.)                 3
1021  Secondary school (e.g. American high school, G...                12
1022           Bachelor’s degree (BA, BS, B.Eng., etc.)                 2
1023        Master’s degree (MA, MS, M.Eng., MBA, etc.)                 6
1024           Bachelor’s degree (BA, BS, B.Eng., etc.)  Less than 1 year
1025        Master’s degree (MA, MS, M.Eng., MBA, etc.)                34
1026           Bachelor’s degree (BA, BS, B.Eng., etc.)                 3
1027                          Primary/elementary school                10
1028           Bachelor’s degree (BA, BS, B.Eng., etc.)                 4
1029  Some college/university study without earning ...                26
1030           Bachelor’s degree (BA, BS, B.Eng., etc.)                 2
1031           Bachelor’s degree (BA, BS, B.Eng., etc.)                15
1032           Bachelor’s degree (BA, BS, B.Eng., etc.)                19
1033           Bachelor’s degree (BA, BS, B.Eng., etc.)                 6
1034  Secondary school (e.g. American high school, G...               NaN
1035        Master’s degree (MA, MS, M.Eng., MBA, etc.)                10
1036           Bachelor’s degree (BA, BS, B.Eng., etc.)               NaN
1037           Bachelor’s degree (BA, BS, B.Eng., etc.)                12
1038           Bachelor’s degree (BA, BS, B.Eng., etc.)                12
1039        Master’s degree (MA, MS, M.Eng., MBA, etc.)                13
1040        Master’s degree (MA, MS, M.Eng., MBA, etc.)                 4
1041           Bachelor’s degree (BA, BS, B.Eng., etc.)                 7
1042        Master’s degree (MA, MS, M.Eng., MBA, etc.)               NaN
1043  Secondary school (e.g. American high school, G...               NaN
1044           Bachelor’s degree (BA, BS, B.Eng., etc.)                 5
1045           Bachelor’s degree (BA, BS, B.Eng., etc.)                 2
1046  Some college/university study without earning ...                 1
1047           Bachelor’s degree (BA, BS, B.Eng., etc.)                20
1048  Secondary school (e.g. American high school, G...                 1
1049  Secondary school (e.g. American high school, G...               NaN
1050           Bachelor’s degree (BA, BS, B.Eng., etc.)                 8

## Response of first 20 respondents to "Student" to "YearsCodePro"

In [85]:
df.loc[:20,"Student":"YearsCodePro"]

,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro
0,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN
1,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN
2,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1
3,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year
4,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9
5,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,Taken an online course in programming or softw...,NaN,Data or business analyst;Data scientist or mac...,13,15,3
6,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...","Just me - I am a freelancer, sole proprietor, ...","Designer;Developer, front-end",6,17,4
7,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN
8,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Database administrator;Developer, back-end;Dev...",12,11,4
9,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10
10,"Yes, full-time",Primary/elementary school,NaN,Contributed to open source software,NaN,NaN,2,11,NaN
11,"Yes, full-time",Some college/university study without earning ...,Mathematics or statistics,Taken an online course in programming or softw...,NaN,Data or business analyst;Data scientist or mac...,5,16,NaN
12,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Data or business analyst;Database administrato...,17,11,8
13,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...",Completed an industry certification program (e...,100 to 499 employees,"Developer, desktop or enterprise applications",13,16,2
14,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,13,NaN
15,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",10,17,3
16,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,20 to 99 employees,"Developer, back-end;Developer, front-end;Devel...",5,18,2
17,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"1,000 to 4,999 employees",Data or business analyst,10,18,3
18,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,100 to 499 employees,"Developer, full-stack",14,13,13
19,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,"1,000 to 4,999 employees","Database administrator;Designer;Developer, bac...",8,17,4
20,NaN,NaN,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,5,11,NaN

## Return the columns names of all the object type columns

In [31]:
df.select_dtypes("object")

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,SOComm,WelcomeChange,SONewContent,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,"Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,"No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,"Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,"No, not at all",NaN,Tech articles written by other developers;Tech...,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,"Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

## Return Feature with most number of Nan values

In [36]:
df.isnull().sum().sum()

1028850

# Devs who gets more than 1800000 find their country, age and thier languageworkedwith?

In [5]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [6]:
df[df["ConvertedComp"]>1800000].loc[:,["Country","Age","LanguageWorkedWith"]]

             Country   Age                                 LanguageWorkedWith
57     United States  47.0                                        C#;Java;SQL
101    United States  37.0              C#;HTML/CSS;JavaScript;SQL;TypeScript
164    United States  30.0  Bash/Shell/PowerShell;Go;HTML/CSS;Java;JavaScr...
434    United States  38.0  Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
450    United States  35.0                                            SQL;VBA
...              ...   ...                                                ...
88162  United States  36.0  Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...
88264  United States  27.0         HTML/CSS;Java;JavaScript;Kotlin;Python;SQL
88266  United States  28.0              C#;HTML/CSS;JavaScript;SQL;TypeScript
88321  United States  26.0                               C++;Python;Scala;SQL
88324  United States  48.0  Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...

[731 rows x 3 columns]

# If devs only earns less than 10000 find their respective country and their edcational background and workingloc?

In [7]:
df[df["ConvertedComp"]<10000].loc[:,["Country","EdLevel","WorkLoc"]]

,Country,EdLevel,WorkLoc
2,Thailand,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Home
24,South Africa,Associate degree,Home
32,Argentina,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",Office
49,India,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Other place, such as a coworking space or cafe"
58,Argentina,Some college/university study without earning ...,Office
...,...,...,...
88174,Brazil,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Office
88257,Egypt,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Office
88295,France,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",Home
88300,Ghana,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Home
88313,Tunisia,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Other place, such as a coworking space or cafe"